services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
#    environment:
#      - VITE_API_BASE_URL=http://127.0.0.1:8000/api/
    depends_on:
      - db
      - back
    restart: always
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee_db
      SPRING_DATASOURCE_USERNAME: adm
      SPRING_DATASOURCE_PASSWORD: Empl0y1Db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: Empl0y1Db
    volumes:
      - postgres_data_adm:/var/lib/postgresql/data

volumes:
  postgres_data_adm:
  node_modules:
